// Grant Programs
export const REQUEST_GRANT_PROGRAM = 'REQUEST_GRANT_PROGRAM';
export const RECIEVE_GRANT_PROGRAM = 'RECIEVE_GRANT_PROGRAM';
export const TOGGLE_RENEW_GRANT_PROGRAM = 'TOGGLE_RENEW_GRANT_PROGRAM';
export const TOGGLE_PROGRAM_CREATOR_STATE = 'TOGGLE_PROGRAM_CREATOR_STATE';
export const PROGRAM_CREATOR_ERRORS_APPEND = 'PROGRAM_CREATOR_ERRORS_APPEND';
export const PROGRAM_CREATOR_ERRORS_CLEAN = 'PROGRAM_CREATOR_ERRORS_CLEAN';


export const REQUEST_TEMPLATES = 'REQUEST_TEMPLATES';
export const RECIEVE_TEMPLATES = 'RECIEVE_TEMPLATES';

// Opinion templates
export const REQUEST_TEMPLATE = 'REQUEST_TEMPLATE';
export const RECIEVE_TEMPLATE = 'RECIEVE_TEMPLATE';

export const TOGGLE_RENEW_TEMPLATE = 'TOGGLE_RENEW_TEMPLATE';
export const TOGGLE_TEMPLATE_EDITOR_STATE = 'TOGGLE_TEMPLATE_EDITOR_STATE';
export const TEMPLATE_EDITOR_CHANGE = 'TEMPLATE_EDITOR_CHANGE';
export const SWITCH_LANG = 'SWITCH_LANG';
export const SET_FIELD_CREATOR_STATE = 'SET_FIELD_CREATOR_STATE';
export const SET_FIELD_CREATOR_VALUES = 'SET_FIELD_CREATOR_VALUES';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';


// Opinion template field
export const REQUEST_FIELD = 'REQUEST_FIELD';
export const RECIEVE_FIELD = 'RECIEVE_FIELD';
export const REQUEST_FIELDS = 'REQUEST_FIELDS';
export const RECIEVE_FIELDS = 'RECIEVE_FIELDS';
export const TOGGLE_RENEW_FIELD = 'TOGGLE_RENEW_FIELD';
export const DELETE_FIELD = 'DELETE_FIELD';
export const SHOW_FIELD_MODAL = 'SHOW_FIELD_MODAL';
export const HIDE_FIELD_MODAL = 'HIDE_FIELD_MODAL';
export const SET_FIELD_EDITOR_STATE = 'SET_FIELD_EDITOR_STATE';
export const SET_FIELD_EDITOR_VALUES = 'SET_FIELD_EDITOR_VALUES';



// Opinion
export const REQUEST_OPINION = 'REQUEST_OPINION';
export const RECIEVE_OPINION = 'RECIEVE_OPINION';
export const SAVE_OPINION = 'SAVE_OPINION';
export const SUBMIT_OPINION = 'SUBMIT_OPINION';
export const SHOW_ERRORS = 'SHOW_ERRORS';
export const SWITCH_QUESTION = 'SWITCH_QUESTION';
export const VALIDATE_QUESTION = 'VALIDATE_QUESTION';




// Common actions
export const RECIEVE_ERROR = 'RECIEVE_ERROR';

